### ISSUE TITLE
How can I contact you?

### ISSUE THREAD

**Issue by alexadam** [calebj0seph/spectro#1]
Hi,
Sorry for opening an issue, but there is no contact info on your profile. I found your awesome project on HN https://news.ycombinator.com/item?id=22505269 and I want to integrate it with https://github.com/alexadam/img-encode. I have a couple of questions, my email is on my profile. Thanks!

**Comment by calebj0seph** [comment]
Hey, feel free to send me a DM on my (unused) Twitter: https://twitter.com/calebj0seph
